### ISSUE TITLE
Reordering issue

### ISSUE THREAD

**Issue by praveenkumartapmobi** [StreetVoice/HysteriaPlayer#102]
Hello Saiday,

As [new version (2.1.5)](https://github.com/StreetVoice/HysteriaPlayer/releases/tag/2.1.5) released with lot of new methods and implementations. I am facing an issue while reordering songs in my Queue.

Like, i've populated all my song data in a TableView. User can pick any song. So, while playing a song, he/she can reorder it. If the user reorder the current playing song, the index of the current items are not changing (I have debugged this) Instead, it works with previous order.

So, how can i manually reset the Index of current song with `HysteriaOrder` method

@saiday For your reference, please try this [SamplePlayer](https://github.com/StreetVoice/HysteriaPlayer/files/109469/SamplePlayer.zip)

**Comment by saiday** [comment]
It's great to see a sample to indicate your issue. thanks.
But I was not able to build your sample, `PlayerCell.h:10:9: 'VYPlayIndicator.h' file not found`

It takes me more time to figure it out, if could, could you please upload new sample?

**Comment by saiday** [comment]
@praveenkumartapmobi it's ok, I fix it by use any dumb view instead. Never mind.

**Comment by saiday** [comment]
@praveenkumartapmobi Thank you, it's a HysteriaPlayer's bug. Been fixed by https://github.com/StreetVoice/HysteriaPlayer/commit/cca13ae31b3ba01cd946125871faf93804ac1eb1.

Please update to 2.1.6 on CocoaPods.

FYI, I made a few changes in your sample to make it work.
In ViewController.m Line 159 ~ 165
```objective-c
- (void)tableView:(UITableView *)tableView moveRowAtIndexPath:(NSIndexPath *)sourceIndexPath toIndexPath:(NSIndexPath *)destinationIndexPath {
    id object = [songRecords objectAtIndex:sourceIndexPath.row];
    [songRecords removeObjectAtIndex:sourceIndexPath.row];
    [songRecords insertObject:object atIndex:destinationIndexPath.row];
    [[HysteriaPlayer sharedInstance] moveItemFromIndex:sourceIndexPath.row toIndex:destinationIndexPath.row];
    [tableView reloadData];
}
```

**Comment by praveenkumartapmobi** [comment]
You can have the "VYPlayIndicator" [here](https://github.com/StreetVoice/HysteriaPlayer/files/109735/Classes.zip)

**Comment by praveenkumartapmobi** [comment]
No, the issue still remains there. As i have told you i have disabled the `[hysteriaPlayer enableMemoryCached:NO];` 

So, when we disable the cachememory in HysteiraPlayer. The, `self.playerItems` will not contains any items. In that case, how could we handle this?

**Comment by saiday** [comment]
@praveenkumartapmobi  Yes, that was a bug. And I just fixed it. 
Please see: https://github.com/StreetVoice/HysteriaPlayer/blob/cca13ae31b3ba01cd946125871faf93804ac1eb1/HysteriaPlayer/HysteriaPlayer.m#L404-L426

**Comment by praveenkumartapmobi** [comment]
Yes, it got fixed. Thanks :)
